subplot(3,4,1);
run firstOrderfalse0/makeConvergencePlot.m;
legend('L_1 magnitude','L_{Inf} magnitude','L_1 order','L_{Inf} order');
subplot(3,4,5);
run firstOrderfalse0.1/makeConvergencePlot.m;
subplot(3,4,9);
run firstOrderfalse2/makeConvergencePlot.m;
subplot(3,4,2);
run firstOrdertrue0/makeConvergencePlot.m;
subplot(3,4,6);
run firstOrdertrue0.1/makeConvergencePlot.m;
subplot(3,4,10);
run firstOrdertrue2/makeConvergencePlot.m;
subplot(3,4,3);
run BarthJespersenfalse0/makeConvergencePlot.m;
subplot(3,4,7);
run BarthJespersenfalse0.1/makeConvergencePlot.m;
subplot(3,4,11);
run BarthJespersenfalse2/makeConvergencePlot.m;
subplot(3,4,4);
run BarthJespersentrue0/makeConvergencePlot.m;
subplot(3,4,8);
run BarthJespersentrue0.1/makeConvergencePlot.m;
subplot(3,4,12);
run BarthJespersentrue2/makeConvergencePlot.m;